

package Analysis;

import Algorithms.chk1;
import Master.MasterPage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author sunsoft
 */
public class Performance extends javax.swing.JFrame {

    /**
     * Creates new form Performance
     */
    public Performance() {
        initComponents();
        chk1 c = new chk1();
        try {
            c.br();
        } catch (IOException ex) {
            Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AccuracyBtn = new javax.swing.JButton();
        AccuracyBtn2 = new javax.swing.JButton();
        AccuracyBtn5 = new javax.swing.JButton();
        AccuracyBtn1 = new javax.swing.JButton();
        AccuracyBtn6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        AccuracyBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AccuracyBtn.setText("Q-Learning");
        AccuracyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccuracyBtnActionPerformed(evt);
            }
        });

        AccuracyBtn2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AccuracyBtn2.setText("Fuzzy Logic");
        AccuracyBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccuracyBtn2ActionPerformed(evt);
            }
        });

        AccuracyBtn5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AccuracyBtn5.setText("Random Forest");
        AccuracyBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccuracyBtn5ActionPerformed(evt);
            }
        });

        AccuracyBtn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AccuracyBtn1.setText("Accuracy");
        AccuracyBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccuracyBtn1ActionPerformed(evt);
            }
        });

        AccuracyBtn6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AccuracyBtn6.setText("Back");
        AccuracyBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccuracyBtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccuracyBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccuracyBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccuracyBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccuracyBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccuracyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccuracyBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccuracyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccuracyBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccuracyBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccuracyBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccuracyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccuracyBtnActionPerformed
        try {
            Graph gr1 = new Graph("Accuracy of Q-Learning");
            gr1.pack();
            RefineryUtilities.centerFrameOnScreen(gr1);
            gr1.setVisible(true);
            gr1.setLocation(0, 100);
        } catch (IOException ex) {
            Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AccuracyBtnActionPerformed

    private void AccuracyBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccuracyBtn2ActionPerformed
        // TODO add your handling code here:
        try {
            Graph2 gr1 = new Graph2("Accuracy of Fuzzy Logic");
            gr1.pack();
            RefineryUtilities.centerFrameOnScreen(gr1);
            gr1.setVisible(true);
            gr1.setLocation(0, 100);
        } catch (IOException ex) {
            Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AccuracyBtn2ActionPerformed

    private void AccuracyBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccuracyBtn5ActionPerformed
        try {
            Graph1 gr1 = new Graph1("Accuracy of Random Forest");
            gr1.pack();
            RefineryUtilities.centerFrameOnScreen(gr1);
            gr1.setVisible(true);
            gr1.setLocation(0, 100);
        } catch (IOException ex) {
            Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AccuracyBtn5ActionPerformed

    private void AccuracyBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccuracyBtn1ActionPerformed
        try {
            Graph4 gr1 = new Graph4("Accuracy");
            gr1.pack();
            RefineryUtilities.centerFrameOnScreen(gr1);
            gr1.setVisible(true);
            gr1.setLocation(0, 100);
        } catch (IOException ex) {
            Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AccuracyBtn1ActionPerformed

    private void AccuracyBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccuracyBtn6ActionPerformed
        MasterPage mp=new MasterPage();
        mp.show();
        this.hide();
    }//GEN-LAST:event_AccuracyBtn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Performance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccuracyBtn;
    private javax.swing.JButton AccuracyBtn1;
    private javax.swing.JButton AccuracyBtn2;
    private javax.swing.JButton AccuracyBtn5;
    private javax.swing.JButton AccuracyBtn6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
